const storage = require('./storage');
const pasarguard = require('./pasarguard');
const pasarguardPanel2 = require('./pasarguard-panel2');
const pasarguardDirect = require('./pasarguard-direct');
const pasarguardDirect2 = require('./pasarguard-direct2');
const planStore = require('./plan-store');

function isTest(order) { const type = String(order.type || order.orderType || '').toLowerCase(); return type === 'test' || type === 'trial' || order.isTest === true || order.planId === 'test'; }
function isPurchase(order) { return !isTest(order); }
function providerId(order) { const provider = String(order.provider || order.backend || order.panelProvider || order.fulfillmentProvider || '').toLowerCase(); const service = String(order.service || order.serviceName || '').toLowerCase(); if (provider === 'pasarguard-panel2' || provider === 'panel2' || provider === 'pasarguard_2' || service === 'gaming' || service.includes('gaming')) return 'pasarguard-panel2'; if (provider === 'pasarguard-direct2' || provider === 'direct2' || provider === 'pasarguard_4' || service === 'direct2' || service.includes('direct 2') || service.includes('direct2')) return 'pasarguard-direct2'; if (provider === 'pasarguard-direct' || provider === 'direct' || provider === 'pasarguard_3' || service === 'direct' || service.includes('direct')) return 'pasarguard-direct'; return 'pasarguard'; }
function providerClient(order) { const id = providerId(order); if (id === 'pasarguard-panel2') return pasarguardPanel2; if (id === 'pasarguard-direct2') return pasarguardDirect2; if (id === 'pasarguard-direct') return pasarguardDirect; return pasarguard; }
function displayName(order) { const plan = order.planName || order.name || 'اشتراک'; const service = order.serviceName || (order.service === 'gaming' ? '🎮 Gaming' : order.service === 'direct2' ? '🎯 Direct 2' : order.service === 'direct' ? '🎯 Direct' : '🛡️ Tunnel'); const marker = isPurchase(order) ? '📦' : '🧪'; return `${marker} ${plan} — ${service}`; }
function status(order) { if (order.paymentStatus === 'REJECTED' || order.fulfillmentStatus === 'FAILED_RETRYABLE' || order.status === 'rejected' || order.status === 'failed') return '❌ ناموفق'; if (order.paymentStatus === 'AWAITING_PAYMENT' || order.paymentStatus === 'AWAITING_RECEIPT' || order.fulfillmentStatus === 'DRAFT' || order.fulfillmentStatus === 'PROVISIONING' || order.status === 'pending' || order.status === 'awaiting_receipt') return '⏳ در انتظار'; if (order.expiresAt || order.expireAt) { const t = new Date(order.expiresAt || order.expireAt).getTime(); if (Number.isFinite(t) && t < Date.now()) return '⌛ منقضی شده'; } return order.fulfillmentStatus === 'FULFILLED' || order.subUrl || order.subscriptionUrl ? '✅ فعال' : '⏳ در انتظار'; }
async function existsInPasarGuard(order) { if (!order?.pasarguardUserId) return false; try { const user = await providerClient(order).getUserById(order.pasarguardUserId); return Boolean(user && (user.id != null || user.username != null)); } catch (error) { if (Number(error?.status) === 404 || /_HTTP_404$/.test(String(error?.message || ''))) return false; throw error; } }
async function listSubscriptions(telegramUserId) { const orders = await storage.listUserOrders(telegramUserId, 100); const candidates = orders.filter(o => o && (o.subUrl || o.subscriptionUrl || o.pasarguardUserId || o.fulfillmentStatus || o.status)); const valid = []; for (const order of candidates) { if (!order.pasarguardUserId) continue; try { if (await existsInPasarGuard(order)) valid.push(order); } catch (error) { console.error(JSON.stringify({ event: 'ACCOUNT_PASARGUARD_CHECK_FAILED', order_id: order.orderId, telegram_user_id: telegramUserId, provider: providerId(order), error: error?.message || String(error) })); } } return valid; }
async function getSubscription(telegramUserId, orderId) { const order = await storage.getOrder(orderId); if (!order || String(order.telegramUserId) !== String(telegramUserId)) return null; if (!(await existsInPasarGuard(order))) return null; const plan = order.planId ? await planStore.get(order.planId) : null; return plan ? { ...order, price: plan.price } : order; }
function canRenew(order) { return isPurchase(order) && order.renewal !== true && Boolean(order.pasarguardUserId) && order.fulfillmentStatus === 'FULFILLED' && order.paymentStatus !== 'REJECTED'; }
function summary(order) { return { id: order.orderId, title: displayName(order), status: status(order), planName: order.planName || order.name || '', service: order.serviceName || order.service || '', traffic: order.traffic || order.trafficLimitBytes || order.trafficBytes || null, duration: order.duration || order.durationDays || null, expiresAt: order.expiresAt || order.expireAt || null, subUrl: order.subUrl || order.subscriptionUrl || null, canRenew: canRenew(order) }; }
module.exports = { listSubscriptions, getSubscription, canRenew, summary, displayName, status, isTest, isPurchase, existsInPasarGuard, providerId };