const { buildUsername } = require('./username');
const { getOrder, updateOrder, saveUser, setState, acquireLock, releaseLock } = require('./storage');
const { getProvider } = require('./providers');
const { createSubscriptionQr } = require('./qr');
const { getConfig, getMessage } = require('./bot-config');
const { getFulfillment } = require('./service-fulfillment');
const crypto = require('crypto');
const { waitUntil } = require('@vercel/functions');
function orderId() { const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, ''); return `TG-${stamp}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`; }
function expiryIso(durationDays) { if (durationDays === null || durationDays === undefined || durationDays === '' || Number(durationDays) === 0) return undefined; return new Date(Date.now() + Number(durationDays) * 86400 * 1000).toISOString(); }
async function deliverSubscription(telegram, order, text, subscriptionUrl) { const config = await getConfig(); const qrBackground = config.bot?.qrBackground || 'bg.png'; const copySubscription = config.buttons?.copySubscription || '📋 کپی لینک اشتراک'; const openSubscription = config.buttons?.openSubscription || '🔗 باز کردن لینک اشتراک'; const fallbackTemplate = await getMessage('subscriptionDeliveryFallback', { sub_url: subscriptionUrl }); const replyMarkup = { inline_keyboard: [[{ text: copySubscription, copy_text: { text: subscriptionUrl } }], [{ text: openSubscription, url: subscriptionUrl }]] }; let qrBuffer = null; try { qrBuffer = await createSubscriptionQr(subscriptionUrl, qrBackground); } catch (error) { console.error(JSON.stringify({ event: 'QR_GENERATION_ERROR', order_id: order.orderId, background: qrBackground, error: error?.message || String(error) })); } try { if (qrBuffer) await telegram.sendPhoto(order.telegramUserId, { source: qrBuffer, filename: 'subscription-qr.png' }, { caption: text, parse_mode: 'HTML', reply_markup: replyMarkup }); else await telegram.sendMessage(order.telegramUserId, text, { parse_mode: 'HTML', reply_markup: replyMarkup }); return true; } catch (error) { try { await telegram.sendMessage(order.telegramUserId, fallbackTemplate, { reply_markup: { inline_keyboard: [[{ text: openSubscription, url: subscriptionUrl }]] } }); return true; } catch { return false; } } }
function isConflict(error) { return Number(error?.status) === 409; }
async function performFulfillment(orderIdValue, telegram) {
  const lockName = `fulfill:${orderIdValue}`; if (!(await acquireLock(lockName, 120))) return { locked: true };
  try {
    let order = await getOrder(orderIdValue); if (!order) throw new Error('ORDER_NOT_FOUND'); if (order.fulfillmentStatus === 'FULFILLED') return { fulfilled: true, order }; if (!['RECEIPT_SUBMITTED', 'PROVISIONING', 'FAILED_RETRYABLE', 'PASARGUARD_USER_CREATED', 'SUBSCRIPTION_RETRIEVED'].includes(order.fulfillmentStatus)) throw new Error('ORDER_NOT_ELIGIBLE');
    const config = await getConfig(); const decision = getFulfillment(order.service, config); if (!decision.ok) { const reason = decision.code || 'SERVICE_PREPARING'; await updateOrder(orderIdValue, { fulfillmentStatus: 'FAILED_RETRYABLE', failureReason: reason }); if (order.telegramUserId) await telegram.sendMessage(order.telegramUserId, await getMessage('serviceUnavailable', { service_name: decision.service?.name || order.service || 'Gaming' })).catch(() => {}); return { fulfilled: false, blocked: true, reason }; }
    const provider = getProvider(decision.provider);
    order = await updateOrder(orderIdValue, { fulfillmentStatus: 'PROVISIONING', failureReason: null, fulfillmentProvider: decision.provider });
    if (order.renewal) {
      if (!order.renewalPasarguardUserId) throw new Error('NO_EXISTING_PASARGUARD_ACCOUNT'); const current = await provider.getUserById(order.renewalPasarguardUserId); const existingExpire = current?.expire ? new Date(current.expire).getTime() : Date.now(); const start = Math.max(Date.now(), existingExpire); const renewalTraffic = Number(order.trafficLimitBytes || order.trafficBytes || 0); const existingLimit = Number(current?.data_limit ?? current?.dataLimit ?? 0); const combinedTraffic = existingLimit === 0 || renewalTraffic === 0 ? 0 : existingLimit + renewalTraffic; const renewalPatch = { status: 'active', data_limit: combinedTraffic, data_limit_reset_strategy: 'no_reset', hwid_limit: order.hwidLimit }; if (order.durationDays !== null && order.durationDays !== undefined && order.durationDays !== '' && Number(order.durationDays) !== 0) renewalPatch.expire = new Date(start + Number(order.durationDays) * 86400 * 1000).toISOString(); await provider.updateUserById(order.renewalPasarguardUserId, renewalPatch); const updated = await provider.getUserById(order.renewalPasarguardUserId); if (!updated?.subscription_url) throw new Error('PASARGUARD_SUBSCRIPTION_URL_MISSING'); order = await updateOrder(orderIdValue, { generatedPasarguardUsername: updated.username || current.username, pasarguardUserId: order.renewalPasarguardUserId, subscriptionUrl: updated.subscription_url, renewalAddedTrafficBytes: renewalTraffic, renewalPreviousTrafficLimitBytes: existingLimit, renewalCombinedTrafficLimitBytes: combinedTraffic, fulfillmentStatus: 'SUBSCRIPTION_RETRIEVED', fulfillmentProvider: decision.provider }); await saveUser({ telegramUserId: order.telegramUserId, username: order.telegramUsername || null, firstName: order.firstName || null, lastName: order.lastName || null, updatedAt: new Date().toISOString(), currentPasarguardUserId: order.renewalPasarguardUserId, currentPasarguardUsername: order.generatedPasarguardUsername, currentSubscriptionUrl: updated.subscription_url, currentOrderId: order.orderId, currentProvider: decision.provider }); order = await updateOrder(orderIdValue, { paymentStatus: 'RECEIPT_SUBMITTED', fulfillmentStatus: 'FULFILLED', fulfilledAt: new Date().toISOString(), deliveryStatus: 'PENDING' }); const renewalText = await getMessage('renewalSuccess', { plan_name: order.planName, username: order.generatedPasarguardUsername, expire: updated.expire || 'بدون انقضا', sub_url: updated.subscription_url }); const delivered = await deliverSubscription(telegram, order, renewalText, updated.subscription_url); await updateOrder(orderIdValue, delivered ? { deliveryStatus: 'DELIVERED' } : { deliveryStatus: 'FAILED', failureReason: 'TELEGRAM_DELIVERY_FAILED' }); return { fulfilled: true, order: await getOrder(orderIdValue) };
    }
    let username = order.generatedPasarguardUsername || buildUsername({ telegramUsername: order.telegramUsername, customName: order.requestedName }); if (username !== order.generatedPasarguardUsername) order = await updateOrder(orderIdValue, { generatedPasarguardUsername: username }); let pgUser = null;
    if (order.pasarguardUserId) pgUser = await provider.getUserById(order.pasarguardUserId); else { for (let attempt = 0; attempt < 10; attempt++) { const existing = await provider.findUserByUsername(username); if (existing) { if (String(existing.note || '').includes(`Order: ${orderIdValue}`)) { pgUser = existing; break; } username = buildUsername({ telegramUsername: order.telegramUsername, customName: order.requestedName }); order = await updateOrder(orderIdValue, { generatedPasarguardUsername: username }); continue; } try { pgUser = await provider.createUser({ username, trafficBytes: order.trafficLimitBytes, expire: expiryIso(order.durationDays), hwidLimit: order.hwidLimit, note: `Order: ${orderIdValue}` }); break; } catch (error) { if (isConflict(error)) { username = buildUsername({ telegramUsername: order.telegramUsername, customName: order.requestedName }); order = await updateOrder(orderIdValue, { generatedPasarguardUsername: username }); continue; } throw error; } } }
    if (!pgUser) throw new Error('PASARGUARD_CREATE_COLLISION_RETRY_EXHAUSTED'); order = await updateOrder(orderIdValue, { generatedPasarguardUsername: pgUser.username || username, pasarguardUserId: pgUser.id, fulfillmentStatus: 'PASARGUARD_USER_CREATED', fulfillmentProvider: decision.provider }); const subscriptionUrl = pgUser.subscription_url || (await provider.getUserById(pgUser.id)).subscription_url; if (!subscriptionUrl) throw new Error('PASARGUARD_SUBSCRIPTION_URL_MISSING'); order = await updateOrder(orderIdValue, { subscriptionUrl, fulfillmentStatus: 'SUBSCRIPTION_RETRIEVED' }); order = await updateOrder(orderIdValue, { paymentStatus: 'RECEIPT_SUBMITTED', fulfillmentStatus: 'FULFILLED', fulfilledAt: new Date().toISOString(), deliveryStatus: 'PENDING' }); await saveUser({ telegramUserId: order.telegramUserId, username: order.telegramUsername || null, firstName: order.firstName || null, lastName: order.lastName || null, updatedAt: new Date().toISOString(), currentPasarguardUserId: pgUser.id, currentPasarguardUsername: order.generatedPasarguardUsername, currentSubscriptionUrl: subscriptionUrl, currentOrderId: order.orderId, currentProvider: decision.provider }); const traffic = order.trafficLimitBytes === 0 ? 'نامحدود ♾️' : formatBytes(order.trafficLimitBytes); const duration = order.durationDays === null || order.durationDays === undefined || order.durationDays === '' || Number(order.durationDays) === 0 ? 'بدون انقضا' : `${order.durationDays} روز`; const successText = await getMessage('subscriptionSuccess', { plan_name: order.planName, traffic, duration, username: order.generatedPasarguardUsername, sub_url: subscriptionUrl }); const delivered = await deliverSubscription(telegram, order, successText, subscriptionUrl); await updateOrder(orderIdValue, delivered ? { deliveryStatus: 'DELIVERED' } : { deliveryStatus: 'FAILED', failureReason: 'TELEGRAM_DELIVERY_FAILED' }); return { fulfilled: true, order: await getOrder(orderIdValue) };
  } catch (error) { const reason = error?.message || String(error); await updateOrder(orderIdValue, { fulfillmentStatus: 'FAILED_RETRYABLE', failureReason: reason }).catch(() => {}); const failedOrder = await getOrder(orderIdValue).catch(() => null); if (failedOrder?.telegramUserId) { await setState('user', failedOrder.telegramUserId, { stage: 'AWAITING_RECEIPT_RETRY', orderId: orderIdValue }); await telegram.sendMessage(failedOrder.telegramUserId, await getMessage('fulfillmentTemporaryFailure')).catch(() => {}); } throw error; } finally { await releaseLock(lockName); }
}
async function fulfillOrder(orderIdValue, telegram) { const task = performFulfillment(orderIdValue, telegram); try { waitUntil(task.catch(() => {})); return { started: true, orderId: orderIdValue }; } catch { return task; } }
async function renewOrder(order, telegram) { return fulfillOrder(order.orderId, telegram); }
function formatBytes(bytes) { const gb = bytes / (1024 ** 3); return Number.isInteger(gb) ? `${gb} گیگابایت` : `${gb.toFixed(1)} گیگابایت`; }
module.exports = { orderId, expiryIso, fulfillOrder, renewOrder, formatBytes };