const BASE_URL = (process.env.PASARGUARD_2_URL || '').replace(/\/+$/, '');
const USERNAME = process.env.PASARGUARD_2_USERNAME;
const PASSWORD = process.env.PASARGUARD_2_PASSWORD;
const REQUEST_TIMEOUT_MS = Number(process.env.PASARGUARD_2_TIMEOUT_MS || 10000);
class PasarGuardPanel2Error extends Error { constructor(message, { status = 0, operation = '', transient = false, details = null } = {}) { super(message); this.name = 'PasarGuardPanel2Error'; this.status = status; this.operation = operation; this.transient = transient; this.details = details; } }
function ensureConfigured() { if (!BASE_URL || !USERNAME || !PASSWORD) throw new PasarGuardPanel2Error('PASARGUARD_2_NOT_CONFIGURED', { operation: 'config' }); }
function safeLog(event, fields = {}) { console.log(JSON.stringify({ event, provider: 'pasarguard-panel2', ...fields })); }
function sanitizeError(value) { if (typeof value === 'string') return value.slice(0, 500); if (!value || typeof value !== 'object') return null; const copy = { ...value }; for (const key of Object.keys(copy)) { if (/password|secret|api.?key|authorization|token|cookie/i.test(key)) delete copy[key]; } return copy; }
function fullSubscriptionUrl(value) { if (!value || typeof value !== 'string') return value; if (/^https?:\/\//i.test(value)) return value; if (value.startsWith('/')) return `${BASE_URL}${value}`; return `${BASE_URL}/${value}`; }
async function request(path, { method = 'GET', token, body, form = false, operation = path } = {}) { ensureConfigured(); const headers = { Accept: 'application/json' }; if (token) headers.Authorization = `Bearer ${token}`; if (form) headers['Content-Type'] = 'application/x-www-form-urlencoded'; else if (body !== undefined) headers['Content-Type'] = 'application/json'; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS); try { const response = await fetch(`${BASE_URL}${path}`, { method, headers, body: form ? new URLSearchParams(body).toString() : body === undefined ? undefined : JSON.stringify(body), signal: controller.signal }); const text = await response.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; } if (!response.ok) { const transient = response.status === 408 || response.status === 425 || response.status === 429 || response.status >= 500; throw new PasarGuardPanel2Error(`PASARGUARD_2_HTTP_${response.status}`, { status: response.status, operation, transient, details: sanitizeError(data) }); } return data; } catch (error) { if (error instanceof PasarGuardPanel2Error) throw error; throw new PasarGuardPanel2Error(error?.name === 'AbortError' ? 'PASARGUARD_2_TIMEOUT' : 'PASARGUARD_2_NETWORK_ERROR', { operation, transient: true }); } finally { clearTimeout(timer); } }
async function authenticate() { const result = await request('/api/admin/token', { method: 'POST', form: true, operation: 'authenticate', body: { username: USERNAME, password: PASSWORD } }); if (!result?.access_token) throw new PasarGuardPanel2Error('PASARGUARD_2_AUTH_TOKEN_MISSING', { operation: 'authenticate' }); return result.access_token; }
async function getGroups(token) { const result = await request('/api/groups/simple', { token, operation: 'get_groups' }); const groups = Array.isArray(result) ? result : (result?.groups || []); const ids = groups.map((group) => Number(group?.id)).filter((id) => Number.isInteger(id)); if (!ids.length) throw new PasarGuardPanel2Error('PASARGUARD_2_NO_GROUPS', { operation: 'get_groups' }); return ids; }
async function findUserByUsername(username) { const token = await authenticate(); try { const user = await request(`/api/user/${encodeURIComponent(username)}`, { token, operation: 'find_user' }); return normalizeUser(user); } catch (error) { if (error.status === 404) return null; throw error; } }
function normalizeUser(user) { if (!user || typeof user !== 'object') return user; if (user.subscription_url) return { ...user, subscription_url: fullSubscriptionUrl(user.subscription_url) }; return user; }
async function createUser({ username, trafficBytes, expire, hwidLimit, note }) { const token = await authenticate(); const groupIds = await getGroups(token); const body = { username, status: 'active', data_limit: trafficBytes, data_limit_reset_strategy: 'no_reset', hwid_limit: hwidLimit, note: note || undefined, group_ids: groupIds, proxy_settings: {} }; if (expire) body.expire = expire; const user = await request('/api/user', { method: 'POST', token, operation: 'create_user', body }); return normalizeUser(user); }
async function getUserById(userId) { const token = await authenticate(); return normalizeUser(await request(`/api/user/by-id/${encodeURIComponent(userId)}`, { token, operation: 'get_user_by_id' })); }
async function updateUserById(userId, patch) { const token = await authenticate(); return normalizeUser(await request(`/api/user/by-id/${encodeURIComponent(userId)}`, { method: 'PUT', token, operation: 'update_user_by_id', body: patch })); }
async function health() { const token = await authenticate(); return Boolean(token); }
module.exports = { PasarGuardPanel2Error, authenticate, getGroups, findUserByUsername, createUser, getUserById, updateUserById, health };