const BASE_URL = (process.env.PASARGUARD_TUNNEL2_URL || '').replace(/\/+$/, '');
const USERNAME = process.env.PASARGUARD_TUNNEL2_USERNAME;
const PASSWORD = process.env.PASARGUARD_TUNNEL2_PASSWORD;
const REQUEST_TIMEOUT_MS = Number(process.env.PASARGUARD_TUNNEL2_TIMEOUT_MS || 10000);
class PasarGuardTunnel2Error extends Error { constructor(message, { status = 0, operation = '', transient = false, details = null } = {}) { super(message); this.name = 'PasarGuardTunnel2Error'; this.status = status; this.operation = operation; this.transient = transient; this.details = details; } }
function ensureConfigured() { if (!BASE_URL || !USERNAME || !PASSWORD) throw new PasarGuardTunnel2Error('PASARGUARD_TUNNEL2_NOT_CONFIGURED', { operation: 'config' }); }
function sanitizeError(value) { if (typeof value === 'string') return value.slice(0, 500); if (!value || typeof value !== 'object') return null; const copy = { ...value }; for (const key of Object.keys(copy)) if (/password|secret|api.?key|authorization|token|cookie/i.test(key)) delete copy[key]; return copy; }
function fullSubscriptionUrl(value) { if (!value || typeof value !== 'string') return value; if (/^https?:\/\//i.test(value)) return value; if (value.startsWith('/')) return `${BASE_URL}${value}`; return `${BASE_URL}/${value}`; }
async function request(path, { method = 'GET', token, body, form = false, operation = path } = {}) { ensureConfigured(); const headers = { Accept: 'application/json' }; if (token) headers.Authorization = `Bearer ${token}`; if (form) headers['Content-Type'] = 'application/x-www-form-urlencoded'; else if (body !== undefined) headers['Content-Type'] = 'application/json'; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS); try { const response = await fetch(`${BASE_URL}${path}`, { method, headers, body: form ? new URLSearchParams(body).toString() : body === undefined ? undefined : JSON.stringify(body), signal: controller.signal }); const text = await response.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; } if (!response.ok) { const transient = response.status === 408 || response.status === 425 || response.status === 429 || response.status >= 500; throw new PasarGuardTunnel2Error(`PASARGUARD_TUNNEL2_HTTP_${response.status}`, { status: response.status, operation, transient, details: sanitizeError(data) }); } return data; } catch (error) { if (error instanceof PasarGuardTunnel2Error) throw error; throw new PasarGuardTunnel2Error(error?.name === 'AbortError' ? 'PASARGUARD_TUNNEL2_TIMEOUT' : 'PASARGUARD_TUNNEL2_NETWORK_ERROR', { operation, transient: true }); } finally { clearTimeout(timer); } }
async function authenticate() { const result = await request('/api/admin/token', { method: 'POST', form: true, operation: 'authenticate', body: { username: USERNAME, password: PASSWORD } }); if (!result?.access_token) throw new PasarGuardTunnel2Error('PASARGUARD_TUNNEL2_AUTH_TOKEN_MISSING', { operation: 'authenticate' }); return result.access_token; }
async function getGroups(token) { const result = await request('/api/groups/simple', { token, operation: 'get_groups' }); const groups = Array.isArray(result) ? result : (result?.groups || []); const ids = groups.map(group => Number(group?.id)).filter(Number.isInteger); if (!ids.length) throw new PasarGuardTunnel2Error('PASARGUARD_TUNNEL2_NO_GROUPS', { operation: 'get_groups' }); return ids; }
function normalizeUser(user) { if (!user || typeof user !== 'object') return user; return user.subscription_url ? { ...user, subscription_url: fullSubscriptionUrl(user.subscription_url) } : user; }
async function findUserByUsername(username) { const token = await authenticate(); try { return normalizeUser(await request(`/api/user/${encodeURIComponent(username)}`, { token, operation: 'find_user' })); } catch (error) { if (error.status === 404) return null; throw error; } }
async function createUser({ username, trafficBytes, expire, hwidLimit, note }) { const token = await authenticate(); const groupIds = await getGroups(token); const body = { username, status: 'active', data_limit: trafficBytes, data_limit_reset_strategy: 'no_reset', hwid_limit: hwidLimit, note: note || undefined, group_ids: groupIds, proxy_settings: {} }; if (expire) body.expire = expire; return normalizeUser(await request('/api/user', { method: 'POST', token, operation: 'create_user', body })); }
async function getUserById(userId) { const token = await authenticate(); return normalizeUser(await request(`/api/user/by-id/${encodeURIComponent(userId)}`, { token, operation: 'get_user_by_id' })); }
async function updateUserById(userId, patch) { const token = await authenticate(); return normalizeUser(await request(`/api/user/by-id/${encodeURIComponent(userId)}`, { method: 'PUT', token, operation: 'update_user_by_id', body: patch })); }
async function health() { const token = await authenticate(); return Boolean(token); }
module.exports = { PasarGuardTunnel2Error, authenticate, getGroups, findUserByUsername, createUser, getUserById, updateUserById, health };