const { Telegraf, Markup } = require('telegraf');
const storage = require('../lib/storage');
const pg = require('../lib/pasarguard');
const { plans, getPlan, customPlan, formatPrice } = require('../lib/plans');
const { normalizeSubscriptionName, buildSubscriptionUsername } = require('../lib/username');
const orders = require('../lib/orders');

const BOT_TOKEN = process.env.BOT_TOKEN;
const ADMIN_ID = String(process.env.ADMIN_ID || '');
const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET;
const BANK_DETAILS = process.env.BANK_DETAILS || 'اطلاعات پرداخت در حال تنظیم است.';
const SUPPORT_USERNAME = process.env.SUPPORT_USERNAME || 'AtiqVPN';
const TEST_TEMPLATE = Number(process.env.PASARGUARD_TEMPLATE_TEST || 0);
const bot = new Telegraf(BOT_TOKEN || '000000000:placeholder');

const html = v => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const admin = ctx => String(ctx.from?.id) === ADMIN_ID;
const log = (event, fields = {}) => console.log(JSON.stringify({ event, ...fields }));
const flowKey = id => `flow:${id}`;
const getFlow = id => storage.getJson(flowKey(id));
const setFlow = (id, v) => storage.setJson(flowKey(id), v, 1800);
const clearFlow = id => storage.deleteKey(flowKey(id));
const userObject = ctx => ({ id: String(ctx.from.id), username: ctx.from.username || null, first_name: ctx.from.first_name || null, last_name: ctx.from.last_name || null });

async function saveUser(ctx, extra = {}) {
  const current = await storage.getUser(ctx.from.id) || { telegram_user_id: String(ctx.from.id), created_at: new Date().toISOString(), test_used: false, pasarguard_user_ids: [] };
  const next = { ...current, username: ctx.from.username || null, first_name: ctx.from.first_name || null, last_name: ctx.from.last_name || null, updated_at: new Date().toISOString(), ...extra };
  await storage.saveUser(next); await storage.addToSet('bot_users', String(ctx.from.id)); return next;
}
async function latestOrder(userId) { const ids = await storage.getSet(`orders:user:${userId}`); const list=[]; for(const id of ids){const o=await storage.getOrder(id); if(o?.fulfillment_status==='FULFILLED') list.push(o);} list.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))); return list[0] || null; }
function standardPlanButtons(prefix='plan') { return plans.map(p=>[Markup.button.callback(`${p.name} - ${formatPrice(p.price)}`, `${prefix}:${p.id}`)]); }
function nameKeyboard(planId) { return Markup.inlineKeyboard([[Markup.button.callback('⚡ نام خودکار', `auto:${planId}`)],[Markup.button.callback('❌ لغو','cancel')]]); }
function usernameError(reason) { return ({ ascii_only:'❌ نام اشتراک فقط می‌تواند شامل حروف انگلیسی، عدد، _ و @ باشد.', spaces:'❌ فاصله مجاز نیست. فقط حروف انگلیسی، عدد، _ و @ مجاز است.', characters:'❌ فقط حروف انگلیسی، عدد، _ و @ مجاز است.', reserved_prefix:'❌ پیشوند TG_ رزرو شده است.', reserved_fallback:'❌ این نام رزرو شده است.', meaningless:'❌ این نام قابل استفاده نیست.', too_short:'❌ نام اشتراک خیلی کوتاه است.' })[reason] || '❌ نام اشتراک قابل قبول نیست.'; }
function receiptOf(m) { if(m.photo?.length) return { type:'photo', file_id:m.photo[m.photo.length-1].file_id, message_id:m.message_id }; if(m.document) return { type:'document', file_id:m.document.file_id, message_id:m.message_id, file_name:m.document.file_name||null }; return null; }
async function notifyReceipt(order) { const caption=`💰 <b>رسید پرداخت جدید</b>\n\nسفارش: <code>${html(order.order_id)}</code>\nکاربر: ${html(order.first_name||'')}\nآیدی: <code>${html(order.telegram_user_id)}</code>\nتلگرام: ${html(order.telegram_username?'@'+order.telegram_username:'ندارد')}\nپلن: <b>${html(order.plan_name)}</b>\nمبلغ: <b>${formatPrice(order.price)}</b>\nنام PasarGuard: <code>${html(order.generated_pasarguard_username)}</code>\n\n⚠️ رسید برای ممیزی است و تأیید دستی شرط fulfillment نیست.`; const kb=Markup.inlineKeyboard([[Markup.button.callback('❌ پرداخت نامعتبر / غیرفعال‌سازی',`invalidate:${order.order_id}`)]]); if(order.receipt_type==='photo') return bot.telegram.sendPhoto(ADMIN_ID,order.receipt_file_id,{caption,parse_mode:'HTML',...kb}); return bot.telegram.sendDocument(ADMIN_ID,order.receipt_file_id,{caption,parse_mode:'HTML',...kb}); }
async function deliver(order, chatId) { const size=order.traffic_limit_bytes===0?'نامحدود':`${(order.traffic_limit_bytes/1024**3).toFixed(2)} GB`; await bot.telegram.sendMessage(chatId,`🎉 <b>اشتراک شما با موفقیت ساخته شد.</b>\n\n📦 سرویس: ${html(order.plan_name)}\n📊 حجم: ${size}\n⏳ انقضا: ${html(order.actual_expire||'طبق PasarGuard')}\n👤 نام اشتراک: <code>${html(order.generated_pasarguard_username)}</code>\n\n🔗 لینک اشتراک:\n<code>${html(order.subscription_url)}</code>`,{parse_mode:'HTML',...Markup.inlineKeyboard([[Markup.button.url('🔗 باز کردن لینک اشتراک',order.subscription_url)]])}); }
async function reportFailure(ctx, order) { await ctx.reply('در حال حاضر در ساخت اشتراک مشکلی پیش آمده است. سفارش شما ثبت شده و در حال بررسی خودکار است.'); try{await bot.telegram.sendMessage(ADMIN_ID,`⚠️ <b>خطای fulfillment</b>\nسفارش: <code>${html(order.order_id)}</code>\nPasarGuard: <code>${html(order.generated_pasarguard_username)}</code>\nخطا: ${html(order.failure_reason||'unknown')}`,{parse_mode:'HTML'});}catch(_){} }
async function makeNewOrder(ctx, plan, requestedName) { const order=await orders.createOrder({telegramUser:userObject(ctx),plan,requestedName}); if(!order.plan_template_id){await orders.updateOrder(order,{fulfillment_status:'FAILED_RECOVERABLE',failure_reason:'plan_template_not_configured'});return ctx.reply('❌ این پلن هنوز به Template مربوطه در PasarGuard متصل نشده است.');} await setFlow(ctx.from.id,{stage:'RECEIPT',orderId:order.order_id}); return ctx.reply(`💳 <b>اطلاعات پرداخت</b>\n\nپلن: <b>${html(plan.name)}</b>\nمبلغ: <b>${formatPrice(plan.price)}</b>\nنام اشتراک: <code>${html(order.generated_pasarguard_username)}</code>\nسفارش: <code>${html(order.order_id)}</code>\n\n${html(BANK_DETAILS)}\n\n📸 رسید را همینجا ارسال کنید. رسید برای ممیزی مدیریت ذخیره می‌شود ولی ساخت اشتراک منتظر تأیید دستی نمی‌ماند.`,{parse_mode:'HTML'}); }
async function makeRenewalOrder(ctx, plan) { const existing=await latestOrder(ctx.from.id); if(!existing?.pasarguard_user_id) return ctx.reply('❌ اشتراک قابل تمدیدی برای حساب شما پیدا نشد.'); const order=await orders.createOrder({telegramUser:userObject(ctx),plan,requestedName:null,fulfillmentType:'renewal',existingPasarguardUserId:existing.pasarguard_user_id,generatedUsername:existing.generated_pasarguard_username}); if(!order.plan_template_id){await orders.updateOrder(order,{fulfillment_status:'FAILED_RECOVERABLE',failure_reason:'plan_template_not_configured'});return ctx.reply('❌ این پلن به Template مربوطه در PasarGuard متصل نشده است.');} await setFlow(ctx.from.id,{stage:'RECEIPT',orderId:order.order_id}); return ctx.reply(`🔄 <b>تمدید اشتراک</b>\n\nاشتراک: <code>${html(existing.generated_pasarguard_username)}</code>\nپلن جدید: <b>${html(plan.name)}</b>\nمبلغ: <b>${formatPrice(plan.price)}</b>\nسفارش: <code>${html(order.order_id)}</code>\n\n${html(BANK_DETAILS)}\n\nرسید را ارسال کنید. نام PasarGuard تغییر نخواهد کرد.`,{parse_mode:'HTML'}); }

bot.start(async ctx=>{await saveUser(ctx);await clearFlow(ctx.from.id);await ctx.reply('👋 به ربات آتی‌کیو‌وی‌پی‌ان خوش آمدید!\n\nلطفاً یکی از گزینه‌های زیر را انتخاب کنید:',Markup.keyboard([['🎁 دریافت اکانت تست'],['🛒 خرید اشتراک'],['👤 حساب من'],['🎯 پشتیبانی']]).resize());});
bot.hears('🛒 خرید اشتراک',async ctx=>{await saveUser(ctx);await ctx.reply('📋 لطفاً بسته مورد نظر را انتخاب کنید:',Markup.inlineKeyboard([...standardPlanButtons(),[Markup.button.callback('🛠 ساخت بسته دلخواه','custom')]]));});
bot.hears('🎯 پشتیبانی',ctx=>ctx.reply(`💬 پشتیبانی: @${SUPPORT_USERNAME}`));
bot.hears('👤 حساب من',async ctx=>{const o=await latestOrder(ctx.from.id);if(!o)return ctx.reply('هنوز اشتراک فعالی برای حساب شما ثبت نشده است.');let u=null;try{u=await pg.getUserById(o.pasarguard_user_id);}catch(_){}const traffic=u?.data_limit??o.traffic_limit_bytes,used=u?.used_traffic??o.used_traffic_bytes,expire=u?.expire??o.actual_expire,url=u?.subscription_url||u?.subscriptionUrl||u?.subscription?.url||o.subscription_url;await ctx.reply(`👤 <b>حساب من</b>\n\nنام اشتراک: <code>${html(u?.username||o.generated_pasarguard_username)}</code>\n📊 حجم: ${traffic===0?'نامحدود':`${(traffic/1024**3).toFixed(2)} GB`}\n📈 مصرف: ${used==null?'نامشخص':`${(used/1024**3).toFixed(2)} GB`}\n⏳ انقضا: ${html(expire||'نامحدود')}\n🔘 وضعیت: ${html(u?.status||o.status||'unknown')}`,{parse_mode:'HTML',...Markup.inlineKeyboard([[Markup.button.url('📥 دریافت لینک اشتراک',url)],[Markup.button.callback('🔄 تمدید اشتراک','renew')]])});});

bot.hears('🎁 دریافت اکانت تست',async ctx=>{const user=await saveUser(ctx);if(user.test_used)return ctx.reply('❌ شما قبلاً اکانت تست دریافت کرده‌اید.');if(!TEST_TEMPLATE)return ctx.reply('❌ اکانت تست هنوز توسط مدیریت تنظیم نشده است.');if(!(await storage.acquireLock(`test:${ctx.from.id}`,90)))return ctx.reply('⏳ درخواست شما در حال پردازش است.');try{let created=null;for(let i=0;i<8;i++){const generated=buildSubscriptionUsername({telegramUsername:ctx.from.username,customName:null});try{created=await pg.createFromTemplate(TEST_TEMPLATE,generated.username,`Telegram test ${ctx.from.id}`);break;}catch(e){if(e.status!==409)throw e;}}if(!created)throw new Error('test_creation_failed');const id=created.id??created.user_id;if(!id)throw new Error('test_user_id_missing');const u=await pg.getUserById(id),url=u.subscription_url||u.subscriptionUrl||u.subscription?.url;if(!url)throw new Error('test_subscription_url_missing');await saveUser(ctx,{test_used:true,test_created_at:new Date().toISOString(),pasarguard_user_ids:[...(user.pasarguard_user_ids||[]),id]});log('TEST_FULFILLED',{telegram_user_id:ctx.from.id,pasarguard_username:u.username});await ctx.reply(`🎁 <b>اکانت تست شما آماده است.</b>\n\n👤 نام اشتراک: <code>${html(u.username)}</code>\n🔗 <code>${html(url)}</code>`,{parse_mode:'HTML',...Markup.inlineKeyboard([[Markup.button.url('🔗 باز کردن لینک اشتراک',url)]])});}catch(e){log('TEST_FAILED',{telegram_user_id:ctx.from.id,error:e.message});await ctx.reply('❌ ساخت اکانت تست موقتاً با مشکل مواجه شد.');}finally{await storage.releaseLock(`test:${ctx.from.id}`);}});

bot.command('pingdb',async ctx=>{if(!admin(ctx))return;try{await storage.setJson('health:ping',{at:Date.now()},10);await ctx.reply('✅ Redis: OK');}catch(e){await ctx.reply(`❌ Redis: ${html(e.message)}`);}});
bot.command('status',async ctx=>{if(!admin(ctx))return;let redis='OK',pasar='OK';try{await storage.setJson('health:status',{at:Date.now()},10);}catch(_){redis='FAIL';}try{if(!pg.configured())throw new Error();await pg.ping();}catch(_){pasar='FAIL';}let pending=0,failed=0;for(const id of await storage.listOrderIds()){const o=await storage.getOrder(id);if(['AWAITING_RECEIPT','PROVISIONING'].includes(o?.fulfillment_status))pending++;if(o?.fulfillment_status==='FAILED_RECOVERABLE')failed++;}await ctx.reply(`🤖 Telegram bot: OK\n🗄 Redis: ${redis}\n🛡 PasarGuard: ${pasar}\n⏳ Pending: ${pending}\n❌ Failed: ${failed}`);});
bot.command('users',async ctx=>{if(!admin(ctx))return;await ctx.reply(`📊 کاربران ثبت‌شده: ${(await storage.listUserIds()).length}`);});
bot.command('orders',async ctx=>{if(!admin(ctx))return;const a=[];for(const id of await storage.listOrderIds()){const o=await storage.getOrder(id);if(o)a.push(o);}a.sort((x,y)=>String(y.created_at).localeCompare(String(x.created_at)));await ctx.reply(a.slice(0,15).map(o=>`<code>${html(o.order_id)}</code> | ${html(o.fulfillment_status)} | <code>${html(o.generated_pasarguard_username)}</code>`).join('\n')||'سفارشی وجود ندارد.',{parse_mode:'HTML'});});
bot.command('failed',async ctx=>{if(!admin(ctx))return;const a=[];for(const id of await storage.listOrderIds()){const o=await storage.getOrder(id);if(o?.fulfillment_status==='FAILED_RECOVERABLE')a.push(o);}await ctx.reply(a.slice(0,15).map(o=>`<code>${html(o.order_id)}</code> | ${html(o.failure_reason||'unknown')}`).join('\n')||'خطای قابل بازیابی وجود ندارد.',{parse_mode:'HTML'});});
bot.command('broadcast',async ctx=>{if(!admin(ctx))return;const text=ctx.message.text.replace(/^\/broadcast\s*/,'').trim();if(!text&&!ctx.message.reply_to_message)return ctx.reply('❌ متن پیام یا Reply لازم است.');let ok=0,fail=0;for(const id of await storage.listUserIds()){try{if(ctx.message.reply_to_message)await ctx.telegram.copyMessage(id,ctx.chat.id,ctx.message.reply_to_message.message_id);else await ctx.telegram.sendMessage(id,text);ok++;await new Promise(r=>setTimeout(r,60));}catch(e){fail++;if(String(e.description||'').includes('blocked'))await storage.removeFromSet('bot_users',id);}}await ctx.reply(`✅ ارسال پایان یافت. موفق: ${ok}\nناموفق: ${fail}`);});

bot.on('callback_query',async ctx=>{const d=String(ctx.callbackQuery.data||'');await ctx.answerCbQuery().catch(()=>{});if(d==='cancel'){await clearFlow(ctx.from.id);return ctx.reply('لغو شد.');}
  if(d.startsWith('plan:')){const p=getPlan(d.slice(5));if(!p)return ctx.reply('❌ پلن نامعتبر است.');await setFlow(ctx.from.id,{stage:'NAME',planId:p.id});return ctx.reply('📝 نام دلخواه اشتراک را وارد کنید؛ یا نام خودکار را انتخاب کنید.',nameKeyboard(p.id));}
  if(d.startsWith('auto:')){const f=await getFlow(ctx.from.id);const p=f?.customPlan&&f.planId===d.slice(5)?f.customPlan:getPlan(d.slice(5));if(!f||!p||f.planId!==p.id)return ctx.reply('❌ این درخواست منقضی شده است.');return makeNewOrder(ctx,p,null);}
  if(d==='custom'){await setFlow(ctx.from.id,{stage:'CUSTOM_TRAFFIC'});return ctx.reply('🛠 حجم را به عدد صحیح گیگابایت وارد کنید (۱ تا ۱۰۰۰).');}
  if(d==='renew'){return ctx.reply('🔄 پلن تمدید را انتخاب کنید:',Markup.inlineKeyboard(standardPlanButtons('renewplan')));}
  if(d.startsWith('renewplan:')){const p=getPlan(d.slice(10));if(!p)return ctx.reply('❌ پلن نامعتبر است.');return makeRenewalOrder(ctx,p);}
  if(d.startsWith('invalidate:')){if(!admin(ctx))return;const o=await storage.getOrder(d.slice(11));if(!o)return ctx.reply('❌ سفارش پیدا نشد.');if(!o.pasarguard_user_id)return ctx.reply('ℹ️ کاربر PasarGuard هنوز ثبت نشده است.');try{await pg.disableUserById(o.pasarguard_user_id,true);await orders.updateOrder(o,{payment_status:'PAYMENT_LATER_REJECTED',fulfillment_status:'PAYMENT_LATER_REJECTED',invalidated_at:new Date().toISOString()},'PAYMENT_INVALIDATED');await bot.telegram.sendMessage(o.telegram_user_id,'❌ پرداخت شما نامعتبر تشخیص داده شد و اشتراک مربوطه غیرفعال شد.');await ctx.reply('✅ اشتراک غیرفعال شد و سفارش برای ممیزی ثبت شد.');}catch(e){log('INVALIDATION_FAILED',{order_id:o.order_id,error:e.message});await ctx.reply('❌ غیرفعال‌سازی انجام نشد.');}}
});

bot.on('message',async ctx=>{await saveUser(ctx);const f=await getFlow(ctx.from.id);if(!f)return;
  if(f.stage==='NAME'){if(!ctx.message.text)return ctx.reply('❌ نام اشتراک را به صورت متن بفرستید.');const n=normalizeSubscriptionName(ctx.message.text);if(!n.ok)return ctx.reply(usernameError(n.reason));const p=f.customPlan&&f.planId===f.customPlan.id?f.customPlan:getPlan(f.planId);if(!p)return ctx.reply('❌ پلن منقضی شده است.');return makeNewOrder(ctx,p,n.value);}
  if(f.stage==='CUSTOM_TRAFFIC'){const n=Number(String(ctx.message.text||'').trim());if(!Number.isInteger(n)||n<1||n>1000)return ctx.reply('❌ حجم باید عدد صحیح بین ۱ تا ۱۰۰۰ باشد.');await setFlow(ctx.from.id,{stage:'CUSTOM_DURATION',traffic:n});return ctx.reply('⏳ مدت را به عدد صحیح روز وارد کنید (۱ تا ۱۵۰ روز).');}
  if(f.stage==='CUSTOM_DURATION'){const n=Number(String(ctx.message.text||'').trim()),p=customPlan(f.traffic,n);if(!p)return ctx.reply('❌ مدت باید عدد صحیح بین ۱ تا ۱۵۰ روز باشد.');await setFlow(ctx.from.id,{stage:'NAME',planId:p.id,customPlan:p});return ctx.reply(`✅ بسته ${f.traffic} گیگابایت / ${n} روز\n💳 ${formatPrice(p.price)}\n\nنام دلخواه را وارد کنید یا نام خودکار را انتخاب کنید.`,nameKeyboard(p.id));}
  if(f.stage==='RECEIPT'){const r=receiptOf(ctx.message);if(!r)return ctx.reply('❌ فقط تصویر یا فایل رسید را ارسال کنید.');const o=await storage.getOrder(f.orderId);if(!o)return ctx.reply('❌ سفارش پیدا نشد.');if(o.receipt_file_id)return ctx.reply('✅ این رسید قبلاً ثبت شده است.');try{const updated=await orders.attachReceipt(o.order_id,r);await clearFlow(ctx.from.id);notifyReceipt(updated).catch(e=>log('ADMIN_RECEIPT_NOTIFY_FAILED',{order_id:o.order_id,error:e.message}));await ctx.reply('✅ رسید دریافت شد. ساخت اشتراک بدون انتظار برای تأیید دستی شروع شد.');try{const fulfilled=updated.fulfillment_type==='renewal'?await orders.renewOrder(o.order_id):await orders.fulfillOrder(o.order_id);await deliver(fulfilled,ctx.chat.id);}catch(e){const failed=await storage.getOrder(o.order_id);await reportFailure(ctx,failed||o);}}catch(e){await ctx.reply('❌ ثبت رسید انجام نشد. لطفاً دوباره ارسال کنید.');}}
});

bot.catch((err,ctx)=>log('BOT_ERROR',{update_type:ctx?.updateType,error:String(err.message||err)}));
module.exports=async(req,res)=>{if(req.method!=='POST')return res.status(200).send('ArtiQ VPN bot is active.');if(WEBHOOK_SECRET&&req.headers['x-telegram-bot-api-secret-token']!==WEBHOOK_SECRET)return res.status(403).send('Unauthorized');try{await bot.handleUpdate(req.body);return res.status(200).send('OK');}catch(e){log('WEBHOOK_ERROR',{error:String(e.message||e)});return res.status(200).send('OK');}};
